feat: Expand hack/lint-mint-embed-sync to cover additional dir
rh-pre-commit.version: 2.4.0
rh-pre-commit.check-secrets: ENABLED

Signed-off-by: Jan Hutar <jhutar@redhat.com>

diff --git a/hack/lint-mint-embed-sync b/hack/lint-mint-embed-sync
--- a/hack/lint-mint-embed-sync
+++ b/hack/lint-mint-embed-sync
@@ -9,17 +9,18 @@ set -euo pipefail
 SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
 
+rc=0
+
 SRC="$REPO_ROOT/internal/mint"
 DST="$REPO_ROOT/internal/dispatch/gcf/mintsrc"
 
-rc=0
 for f in "$SRC"/*; do
     name="$(basename "$f")"
     if [[ "$name" == *_test.go ]]; then
         continue
     fi
 
-    # "go.mod" is a special case since commit eecac658c
+    # "go.mod" special case since commit eecac658c
     if [[ "$name" == "go.mod" ]]; then
         ff="$( mktemp )"
         sed 's| => ../mintcore$| => ./mintcore|' "$f" >"$ff"
@@ -28,6 +29,24 @@ for f in "$SRC"/*; do
 
     if ! cmp -s "$f" "$DST/$name.embed"; then
         echo "DESYNC: internal/mint/$name != internal/dispatch/gcf/mintsrc/$name.embed" >&2
+        rc=1
+    fi
+
+    # "go.mod" special case cleanup
+    [[ "$name" == "go.mod" ]] && rm "$f"
+done
+
+SRC="$REPO_ROOT/internal/mintcore"
+DST="$REPO_ROOT/internal/dispatch/gcf/mintsrc/mintcore"
+
+for f in "$SRC"/*; do
+    name="$(basename "$f")"
+    if [[ "$name" == *_test.go ]]; then
+        continue
+    fi
+
+    if ! cmp -s "$f" "$DST/$name.embed"; then
+        echo "DESYNC: internal/mintcore/$name != internal/dispatch/gcf/mintsrc/mintcore/$name.embed" >&2
         rc=1
     fi
 done
